Add web as a platform (#623)
Signed-off-by: James Orson <jamesaorson@gmail.com>

diff --git a/.github/workflows/autobutler-release.yml b/.github/workflows/autobutler-release.yml
--- a/.github/workflows/autobutler-release.yml
+++ b/.github/workflows/autobutler-release.yml
@@ -6,22 +6,47 @@ on:
 defaults:
   run:
     shell: bash
+
+env:
+  AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
+  WORKING_DIR: ${{ github.workspace }}
+
 jobs:
   autobutler-release:
     runs-on: ubuntu-latest
+    permissions:
+      contents: write
     steps:
-      - name: Workflow Dispatch
-        uses: actions/github-script@v7
+      - name: Check tag format
+        run: |
+          if [[ ! "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Tag must be in the format vX.Y.Z"
+            exit 1
+          fi
+      - name: Checkout code
+        uses: actions/checkout@v6
         with:
-          github-token: ${{ secrets.FG_PAT }}
-          script: |
-            const tag = context.ref.replace('refs/tags/', '');
-            github.rest.actions.createWorkflowDispatch({
-              owner: 'autobutler-org',
-              repo: 'autobutler.org',
-              workflow_id: 'release.yml',
-              ref: 'main',
-              inputs: {
-                tag: tag,
-              }
-            });
+          ref: ${{ github.ref_name }}
+          fetch-depth: 0
+          fetch-tags: true
+      - name: Setup Flutter
+        uses: ./.github/actions/setup-flutter
+      - name: Build frontend [web]
+        run: |
+          make build/frontend/web
+      - name: Run GoReleaser
+        uses: goreleaser/goreleaser-action@v6
+        with:
+          # either 'goreleaser' (default) or 'goreleaser-pro'
+          distribution: goreleaser
+          # 'latest', 'nightly', or a semver
+          version: ~> v2
+          args: release --clean
+          workdir: ${{ env.WORKING_DIR }}
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+      - name: Upload assets
+        uses: actions/upload-artifact@v4
+        with:
+          name: autobutler-release
+          path: ${{ env.WORKING_DIR }}/dist/*
